
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iafmcjyqqgmtreeogwqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhZm1janlxcWdtdHJlZW9nd3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMzk1MzMsImV4cCI6MjA1NjgxNTUzM30.Sy9NbXDbOhnFalHDdEQf7XKHUo17QdDf_Oz2Y7bnJXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    db: {
      schema: 'public'
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false
    }
  }
);

// Set up global real-time subscriptions for shops and products
export const setupRealtimeSubscriptions = () => {
  // Subscribe to changes in shops
  supabase.channel('shops-channel')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'shops' }, (payload) => {
      console.log('Real-time update on shops table:', payload);
    })
    .subscribe();

  // Subscribe to changes in products
  supabase.channel('products-channel')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'products' }, (payload) => {
      console.log('Real-time update on products table:', payload);
    })
    .subscribe();
};
